import type { BuildingId, GameState } from '../state';
import {
  BUILDINGS,
  energyProduction,
  energyUpkeep,
  fuelProduction,
  fuelUpkeep,
  lumenOutput,
  materialsProduction,
  exoticProduction,
  exoticRequired,
  maintenanceUpkeep,
} from '../game/buildings';
import { addResource, spendResource } from '../game/resources';
import { researchLumenMultiplier } from '../game/research';
import { activeEventEffect } from '../game/events';
import { advancePhase } from './progression';

export const DEFAULT_DAY_LENGTH = 1 / 120; // one full day/night cycle per 120 ticks

/** How much light it takes for the current scene to read as fully lit (render/*.ts). Gates the Orbital Mirror's leave-the-ground unlock. */
export const FULL_LIGHT_SCALE = 50_000_000;

/** Materials' lumen-efficiency nudge (issue #2): materialsEfficiency = 1 + MAT_LUMEN_K * log10(1 + materials). */
const MAT_LUMEN_K = 0.04;

export interface EnergyResolution {
  energyProduced: number;
  energyConsumed: number;
  /** Fraction of demand actually powered, clamped to [0, 1] — the soft brownout ratio (issue #1). */
  energyRatio: number;
  /** Convenience derived flag: true once energyRatio reaches 1 (no brownout). */
  consumersActive: boolean;
  /** Energy actually flowing this tick (no storage buffer — this is a live balance, not a stockpile). */
  energySurplus: number;
}

export interface StockpileResolution {
  produced: number;
  consumed: number;
  /** Fraction of demand the stockpile plus this tick's production actually covers, clamped to [0, 1] — fuel's own brownout ratio, mirroring energy's. */
  fuelRatio: number;
  /** True once fuelRatio reaches 1 (no brownout) — kept for callers that only care about the binary "fully fed" case. */
  active: boolean;
}

export interface ExoticGateResolution {
  produced: number;
  /** Total exotic matter reserve all owned era-8+ lights require — a capability threshold, not a per-tick draw. */
  demand: number;
  /** Fraction of that demand the current stockpile covers, clamped to [0, 1] — exotic lights dim by this ratio (issue #6). */
  exoticRatio: number;
}

/**
 * Resolves this tick's energy balance. Electric Age through Nuclear Age
 * lights consume energy, generated by the era 4/5/7 power buildings (which
 * in turn burn fuel — see resolveFuel). There's no battery, but unlike a
 * stockpile, a deficit dims output proportionally instead of idling every
 * consumer (issue #1: energy is the real-time soft limiter). A power
 * building whose fuel input is running short scales its own output down by
 * the same fuelRatio (see resolveFuel below) rather than cutting off at once.
 */
export function resolveEnergy(state: GameState, fuelRatio: number = resolveFuel(state).fuelRatio): EnergyResolution {
  let energyProduced = 0;
  let energyConsumed = 0;
  for (const id of Object.keys(BUILDINGS) as BuildingId[]) {
    const owned = state.buildings[id];
    const def = BUILDINGS[id];
    energyProduced += def.fuelConsumedPerUnit > 0 ? energyProduction(id, owned) * fuelRatio : energyProduction(id, owned);
    energyConsumed += energyUpkeep(id, owned);
  }
  const energyRatio = energyConsumed > 0 ? Math.min(1, energyProduced / energyConsumed) : 1;
  const consumersActive = energyRatio >= 1;
  const energySurplus = consumersActive ? energyProduced - energyConsumed : 0;

  return { energyProduced, energyConsumed, energyRatio, consumersActive, energySurplus };
}

/** Signed energy slack: produced minus consumed. Negative means a deficit. */
export function energyHeadroom(state: GameState): number {
  const { energyProduced, energyConsumed } = resolveEnergy(state);
  return energyProduced - energyConsumed;
}

/** True if buying one more `id` would still leave enough power to run it. Buildings that don't consume energy are always powerable. */
export function canPowerBuilding(state: GameState, id: BuildingId): boolean {
  const consumed = BUILDINGS[id].energyConsumedPerUnit;
  if (consumed <= 0) {
    return true;
  }
  return energyHeadroom(state) >= consumed;
}

/**
 * Resolves this tick's fuel balance (Gas Age's Gas Works refines it; gas
 * lamps and the era 4/5/7 power buildings burn it). Fuel is a stockpile
 * (carries over between ticks), but consumers now dim proportionally
 * instead of hard-idling the instant the stockpile can't cover demand —
 * a binary cutoff meant adding one more fuel-burner past the tipping point
 * collapsed every consumer at once, drained the stockpile to empty, then
 * let it refill while everything sat idle, oscillating "on, off, on, off"
 * (reported bug: power generation went inconsistent after adding Power
 * Plants). Mirrors resolveEnergy's brownout ratio.
 */
export function resolveFuel(state: GameState): StockpileResolution {
  let produced = 0;
  let consumed = 0;
  for (const id of Object.keys(BUILDINGS) as BuildingId[]) {
    const owned = state.buildings[id];
    produced += fuelProduction(id, owned);
    consumed += fuelUpkeep(id, owned);
  }
  const fuelRatio = consumed > 0 ? Math.min(1, (state.resources.fuel + produced) / consumed) : 1;
  const active = fuelRatio >= 1;
  return { produced, consumed, fuelRatio, active };
}

/**
 * Resolves this tick's exotic matter position (Fusion Age on: harvested by
 * each era's secondary building). Unlike fuel, exotic matter is a
 * capability gate, not a flow: lights compare the total reserve their owned
 * units require against the stockpile, but the stockpile itself is never
 * spent down — it's the installed infrastructure backing them (issue #6).
 */
export function resolveExotic(state: GameState): ExoticGateResolution {
  let produced = 0;
  let demand = 0;
  for (const id of Object.keys(BUILDINGS) as BuildingId[]) {
    const owned = state.buildings[id];
    produced += exoticProduction(id, owned);
    demand += exoticRequired(id, owned);
  }
  const exoticRatio = demand > 0 ? Math.min(1, state.resources.exotic / demand) : 1;
  return { produced, demand, exoticRatio };
}

/** Total ambient light currently produced by all owned buildings. Energy-, fuel-, or exotic-starved consumers dim proportionally rather than going dark all at once. */
export function totalLightOutput(state: GameState): number {
  const fuel = resolveFuel(state);
  const { energyRatio } = resolveEnergy(state, fuel.fuelRatio);
  const { exoticRatio } = resolveExotic(state);
  let lumens = 0;
  for (const id of Object.keys(BUILDINGS) as BuildingId[]) {
    const def = BUILDINGS[id];
    let output = lumenOutput(id, state.buildings[id]);
    if (def.energyConsumedPerUnit > 0) {
      output *= energyRatio;
    }
    if (def.fuelConsumedPerUnit > 0) {
      output *= fuel.fuelRatio;
    }
    if (def.exoticRequiredPerUnit > 0) {
      output *= exoticRatio;
    }
    lumens += output;
  }
  return lumens;
}

/** True once total light output has reached the threshold the current scene reads as fully lit. Gates the Orbital Mirror's leave-the-ground unlock. */
export function isSceneFullyLit(state: GameState): boolean {
  return totalLightOutput(state) >= FULL_LIGHT_SCALE;
}

/** Below this much total light, civilization brightness is negligible and doesn't suppress darkness. */
const LUMEN_SUPPRESS_START = 1e12;
/** At or above this much total light, the suppression ramp (lumenSuppressionRatio) reaches its raw maximum of 1. */
const LUMEN_SUPPRESS_FULL = 1e15;

/**
 * Raw (uncapped) 0..1 log ramp of how bright the civilization currently
 * reads, between LUMEN_SUPPRESS_START and LUMEN_SUPPRESS_FULL — hosted here
 * (rather than darkness.ts or progression.ts) because both of those already
 * depend on this module for totalLightOutput, and this avoids an
 * automation→progression→darkness→automation import cycle. Used both as
 * darkness.ts's lumen-suppression input (issue #4, capped there at
 * MAX_LUMEN_SUPPRESSION) and as progression.ts's "planet fully lit" gate for
 * the Orbital Mirror (issue #8).
 */
export function lumenSuppressionRatio(state: GameState): number {
  const light = totalLightOutput(state);
  if (light <= LUMEN_SUPPRESS_START) {
    return 0;
  }
  const t =
    (Math.log10(light) - Math.log10(LUMEN_SUPPRESS_START)) /
    (Math.log10(LUMEN_SUPPRESS_FULL) - Math.log10(LUMEN_SUPPRESS_START));
  return Math.min(1, Math.max(0, t));
}

/** Fraction of the way the planet's night sky reads as fully lit — the Orbital Mirror's civilization-milestone gate (issue #8), in place of the raw totalLightOutput number. */
export function planetLitFraction(state: GameState): number {
  return lumenSuppressionRatio(state);
}

/** Materials produced this tick by all owned buildings (a stockpile, unlike energy's live balance). */
export function totalMaterialsOutput(state: GameState): number {
  let materials = 0;
  for (const id of Object.keys(BUILDINGS) as BuildingId[]) {
    materials += materialsProduction(id, state.buildings[id]);
  }
  return materials;
}

/** Lumens owed in upkeep this tick by all owned buildings — a late-game sink so unchecked growth eventually plateaus (issue #9). */
export function totalMaintenanceUpkeep(state: GameState): number {
  let maintenance = 0;
  for (const id of Object.keys(BUILDINGS) as BuildingId[]) {
    maintenance += maintenanceUpkeep(id, state.buildings[id]);
  }
  return maintenance;
}

/**
 * Advances the simulation by one tick: produces resources from buildings,
 * resolves the energy/fuel/exotic balances, advances the day/night clock,
 * and checks phase progression. `dayStep` lets callers control cycle speed
 * (used by tests); production-line callers can rely on the default.
 */
export function tick(state: GameState, dayStep: number = DEFAULT_DAY_LENGTH): GameState {
  let next = state;

  // Happiness gates lumen production, convexly but with a floor: an unhappy
  // population works the lights less effectively, not just proportionally
  // less - half happiness should feel like more than half output - but it
  // can never collapse to zero (a bare happiness**2 was too punishing on
  // mid-low happiness; **1.5 is gentler while the 0.5 floor still keeps it
  // meaningful without being catastrophic). systems/happiness.ts is the
  // only place happiness is written; this is the only place it's read for
  // output.
  const materialsEfficiency = 1 + MAT_LUMEN_K * Math.log10(1 + state.resources.materials);
  const lumenMultiplier =
    researchLumenMultiplier(state) *
    (0.5 + 0.5 * state.resources.happiness ** 1.5) *
    materialsEfficiency *
    activeEventEffect(state).lumenProductivityMult;
  const grossLumens = totalLightOutput(state) * lumenMultiplier;
  const maintenance = totalMaintenanceUpkeep(state);
  const lumens = Math.max(-state.resources.lumens, grossLumens - maintenance);
  if (lumens !== 0) {
    next = addResource(next, 'lumens', lumens);
  }

  const materials = totalMaterialsOutput(state);
  if (materials !== 0) {
    next = addResource(next, 'materials', materials);
  }

  const fuel = resolveFuel(state);
  if (fuel.produced !== 0) {
    next = addResource(next, 'fuel', fuel.produced);
  }
  // Only draw what's actually covered (consumed * fuelRatio): under a
  // brownout this drains the stockpile gradually toward a steady state
  // instead of demanding more than exists and crashing it to zero.
  const fuelDrawn = fuel.consumed * fuel.fuelRatio;
  if (fuelDrawn !== 0) {
    next = spendResource(next, 'fuel', fuelDrawn);
  }

  const exotic = resolveExotic(state);
  if (exotic.produced !== 0) {
    next = addResource(next, 'exotic', exotic.produced);
  }

  const { energySurplus } = resolveEnergy(state, fuel.fuelRatio);

  next = advancePhase({
    ...next,
    tick: next.tick + 1,
    dayNightClock: (next.dayNightClock + dayStep) % 1,
    resources: { ...next.resources, energy: energySurplus },
  });

  return next;
}
